<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Pegawai;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        $pegawai = Pegawai::factory()->create([
            'nama_pegawai' => 'Admin',
            'noidentitas' => '12345678',
            'nomorindukpegawai' => '12345678',
            'is_admin' => true,
        ]);

        $adminUser = User::factory()->create([
            'pegawai_id' => $pegawai->pegawai_id,
            'username' => 'admin',
            'password' => \Illuminate\Support\Facades\Hash::make('admin123'),
            'statusaktif' => true,
        ]);

        $pegawai->update(['loginuser_id' => $adminUser->loginuser_id]);

        $dataPegawai =
            [
                [
                    'nama_pegawai' => 'HETTYANA MALINDAh PARDOSI',
                    'noidentitas' => '3578145702880002',
                    'nomorindukpegawai' => '198802172025212073',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12393,
                    'kelurahan_id' => 14588,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '1988-02-17',
                    'jeniskelamin' => 'PEREMPUAN',
                    'statusperkawinan' => 'KAWIN',
                    'alamat_pegawai' => 'JOJORAN BARU GANG 2 / NO. 03 SURABAYA',
                    'agama' => 'PROTESTAN',
                    'alamatemail' => 'anapardosi1702@gmail.com / anapardosi88@gmail.com',
                    'notelp_pegawai' => '081333338938',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => null,
                    'beratbadan' => null,
                ],
                [
                    'nama_pegawai' => 'RONNY BAEHAQI, drg.,Sp.BMMF,Subsp.T.M.T.M.J (K)',
                    'noidentitas' => '3510152211710001',
                    'nomorindukpegawai' => '197112222002121004',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12408,
                    'kelurahan_id' => 14654,
                    'tempatlahir_pegawai' => 'Bandung',
                    'tgl_lahirpegawai' => '1971-11-22',
                    'jeniskelamin' => 'LAKI-LAKI',
                    'statusperkawinan' => 'KAWIN',
                    'alamat_pegawai' => 'ketintang madya kencana 1 nomer 28',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'ronbyhaqi@gmail.com',
                    'notelp_pegawai' => '081934769139',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 175,
                    'beratbadan' => 75,
                ],
                [
                    'nama_pegawai' => 'Zulfikar Afdal Rusdi',
                    'noidentitas' => '3578041106940004',
                    'nomorindukpegawai' => '199406112025211109',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 551,
                    'kecamatan_id' => 12167,
                    'kelurahan_id' => 18426,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '1994-06-11',
                    'jeniskelamin' => 'LAKI-LAKI',
                    'statusperkawinan' => 'BELUM KAWIN',
                    'alamat_pegawai' => 'jl kalibader',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'rusdizulfikar07@gmail.com',
                    'notelp_pegawai' => '081335190977',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 168,
                    'beratbadan' => 88,
                ],
                [
                    'nama_pegawai' => 'FARIKHA ISTANIA A.Md,Kep',
                    'noidentitas' => '351509407860001',
                    'nomorindukpegawai' => '301140719860720180311',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 551,
                    'kecamatan_id' => 12170,
                    'kelurahan_id' => 18504,
                    'tempatlahir_pegawai' => 'SIDOARJO',
                    'tgl_lahirpegawai' => '1986-07-14',
                    'jeniskelamin' => 'PEREMPUAN',
                    'statusperkawinan' => null,
                    'alamat_pegawai' => '',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'istania44@gmail.com',
                    'notelp_pegawai' => '08113000583',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => null,
                    'beratbadan' => null,
                ],
                [
                    'nama_pegawai' => 'Mochamad Sahid',
                    'noidentitas' => '3578153008930005',
                    'nomorindukpegawai' => '199308302025211121',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12398,
                    'kelurahan_id' => 14607,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '1993-08-30',
                    'jeniskelamin' => 'LAKI-LAKI',
                    'statusperkawinan' => 'BELUM KAWIN',
                    'alamat_pegawai' => 'Krembangan Jaya Selatan IIa No. 8',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'mosahid002@gmail.com',
                    'notelp_pegawai' => '082338404527',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 163.5,
                    'beratbadan' => 75,
                ],
                [
                    'nama_pegawai' => 'MIRA MELYNDA PRAKOSA, S.Kep.Ns',
                    'noidentitas' => '3578035105940002',
                    'nomorindukpegawai' => '153578035105940002',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12403,
                    'kelurahan_id' => 14628,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '1994-05-11',
                    'jeniskelamin' => 'PEREMPUAN',
                    'statusperkawinan' => 'KAWIN',
                    'alamat_pegawai' => 'Jl. Medayu Utara 7/12',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'miramelyndaprakosa@gmail.com',
                    'notelp_pegawai' => '81330045472',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 161,
                    'beratbadan' => 56,
                ],
                [
                    'nama_pegawai' => 'FISHA FLOURENSIA',
                    'noidentitas' => '3572016509990002',
                    'nomorindukpegawai' => '133572016509990002',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 521,
                    'kecamatan_id' => 12282,
                    'kelurahan_id' => 12357,
                    'tempatlahir_pegawai' => 'BLITAR',
                    'tgl_lahirpegawai' => '1999-09-25',
                    'jeniskelamin' => 'PEREMPUAN',
                    'statusperkawinan' => 'BELUM KAWIN',
                    'alamat_pegawai' => 'Jalan Asem Bagus 2 No. 47',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'fflourensia@gmail.com',
                    'notelp_pegawai' => '085730136540',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 170,
                    'beratbadan' => 63,
                ],
                [
                    'nama_pegawai' => 'PRIMASITHA MAHARANY HARSOYO PUTRI Sp.Jp',
                    'noidentitas' => '3578044809930003',
                    'nomorindukpegawai' => '133578044809930003',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12403,
                    'kelurahan_id' => 14631,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '1993-09-08',
                    'jeniskelamin' => 'PEREMPUAN',
                    'statusperkawinan' => null,
                    'alamat_pegawai' => 'Wonorejo Asri XI - K6',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'sitha.maharani@yahoo.com',
                    'notelp_pegawai' => '081234560891',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => null,
                    'beratbadan' => null,
                ],
                [
                    'nama_pegawai' => 'WHIKKE AYU NINGSARI',
                    'noidentitas' => '3578106601870004',
                    'nomorindukpegawai' => '198701262025212031',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12410,
                    'kelurahan_id' => 14670,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '1987-01-26',
                    'jeniskelamin' => 'PEREMPUAN',
                    'statusperkawinan' => 'KAWIN',
                    'alamat_pegawai' => 'Jl. Kedung Sroko 7 No. 30',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'whikkeayu@gmail.com',
                    'notelp_pegawai' => '087853737818',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 155,
                    'beratbadan' => 55,
                ],
                [
                    'nama_pegawai' => 'ELIKA DWI PUTRI TRESANTI',
                    'noidentitas' => '3578295904940002',
                    'nomorindukpegawai' => '199404192024212002',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12397,
                    'kelurahan_id' => 14605,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '1994-04-19',
                    'jeniskelamin' => 'PEREMPUAN',
                    'statusperkawinan' => 'CERAI HIDUP',
                    'alamat_pegawai' => 'Kedinding Lor Gang Manggis Nomor 39',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'elikarmdn@gmail.com',
                    'notelp_pegawai' => '081232786634',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 162,
                    'beratbadan' => 66,
                ],
                [
                    'nama_pegawai' => 'AGUS WIDOYONO',
                    'noidentitas' => '3578046608170007',
                    'nomorindukpegawai' => '196608172007011020',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12416,
                    'kelurahan_id' => 14701,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '1966-08-17',
                    'jeniskelamin' => 'LAKI-LAKI',
                    'statusperkawinan' => 'DUDA',
                    'alamat_pegawai' => 'Jln.bratang gede kali sumo no.47, RT 09 RW 12, Kel/Desa Ngagel rejo, Kec. Wonokromo',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'Positif -',
                    'notelp_pegawai' => '081231007266',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => null,
                    'beratbadan' => null,
                ],
                [
                    'nama_pegawai' => 'AMAL ARIFI HIDAYAT Sp.PD.',
                    'noidentitas' => '3578092612930005',
                    'nomorindukpegawai' => '133578092612930005',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12408,
                    'kelurahan_id' => 14654,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '1993-12-26',
                    'jeniskelamin' => 'LAKI-LAKI',
                    'statusperkawinan' => null,
                    'alamat_pegawai' => '',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'Positif 1',
                    'notelp_pegawai' => '08785178092',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => null,
                    'beratbadan' => null,
                ],
                [
                    'nama_pegawai' => 'AYU PAMUNGKAS  A.Md,Kep',
                    'noidentitas' => '1705065606000001',
                    'nomorindukpegawai' => '151705065606000001',
                    'provinsi_id' => 4,
                    'kabupaten_id' => 728,
                    'kecamatan_id' => 13141,
                    'kelurahan_id' => 24161,
                    'tempatlahir_pegawai' => 'RIAU',
                    'tgl_lahirpegawai' => '2000-06-16',
                    'jeniskelamin' => 'PEREMPUAN',
                    'statusperkawinan' => 'BELUM KAWIN',
                    'alamat_pegawai' => 'Jalan Jojoran I Blok AA No. 5, RT.15/RW.8, Mojo, Gubeng',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'ayupamungkas281@gmail.com',
                    'notelp_pegawai' => '081278123314',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 163,
                    'beratbadan' => 57,
                ],
                [
                    'nama_pegawai' => 'BAMBANG PRIYONO S.Kep.Ns',
                    'noidentitas' => '3515081301870005',
                    'nomorindukpegawai' => '198701132010011006',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 551,
                    'kecamatan_id' => 12171,
                    'kelurahan_id' => 18515,
                    'tempatlahir_pegawai' => 'Banyuwangi',
                    'tgl_lahirpegawai' => '1987-01-13',
                    'jeniskelamin' => 'LAKI-LAKI',
                    'statusperkawinan' => 'KAWIN',
                    'alamat_pegawai' => 'Perum Kenari Residence E-9 Tambakrejo Waru Sidoarjo',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'bamsluphitomardi@gmail.com',
                    'notelp_pegawai' => '082264189118',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 170,
                    'beratbadan' => 70,
                ],
                [
                    'nama_pegawai' => 'NUR ASDI MARSONY',
                    'noidentitas' => '3514120803740003',
                    'nomorindukpegawai' => '197408032007011012',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 547,
                    'kecamatan_id' => 12076,
                    'kelurahan_id' => 17019,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '1974-08-03',
                    'jeniskelamin' => 'LAKI-LAKI',
                    'statusperkawinan' => 'KAWIN',
                    'alamat_pegawai' => 'PABEAN GANG ANGGREK, RT 004 RW 004, Kel/Desa KEJAPANAN, Kec. Gempol',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'Positif -',
                    'notelp_pegawai' => '085649257473',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => null,
                    'beratbadan' => null,
                ],
                [
                    'nama_pegawai' => 'SUPARNI',
                    'noidentitas' => '3501111707860002',
                    'nomorindukpegawai' => '198607172025211135',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12393,
                    'kelurahan_id' => 14588,
                    'tempatlahir_pegawai' => 'Pacitan',
                    'tgl_lahirpegawai' => '1986-07-17',
                    'jeniskelamin' => 'LAKI-LAKI',
                    'statusperkawinan' => 'DUDA',
                    'alamat_pegawai' => 'JOJORAN 3A BLOK 7 NO.9 RT/RW :014/012 Kel/Desa : MOJO ,Kecamatan : GUBENG',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'suparniko@gmail.com',
                    'notelp_pegawai' => '0881306823301',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 176,
                    'beratbadan' => 50,
                ],
                [
                    'nama_pegawai' => 'MAUFIZA  Amd.Rad',
                    'noidentitas' => '1172016301000003',
                    'nomorindukpegawai' => '151172016301000003',
                    'provinsi_id' => 1,
                    'kabupaten_id' => 847,
                    'kecamatan_id' => 14698,
                    'kelurahan_id' => 45993,
                    'tempatlahir_pegawai' => 'KOTA SABANG',
                    'tgl_lahirpegawai' => '2000-01-23',
                    'jeniskelamin' => 'PEREMPUAN',
                    'statusperkawinan' => 'BELUM KAWIN',
                    'alamat_pegawai' => '',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'maufiza23januari@gmail.com',
                    'notelp_pegawai' => '082272476746',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 152,
                    'beratbadan' => 43,
                ],
                [
                    'nama_pegawai' => 'BAGHASE PRASETYO',
                    'noidentitas' => '1802072705020007',
                    'nomorindukpegawai' => '151802072705020007',
                    'provinsi_id' => 8,
                    'kabupaten_id' => 690,
                    'kecamatan_id' => 14102,
                    'kelurahan_id' => 36348,
                    'tempatlahir_pegawai' => 'YUKUM JAYA',
                    'tgl_lahirpegawai' => '2002-05-27',
                    'jeniskelamin' => 'LAKI-LAKI',
                    'statusperkawinan' => 'BELUM KAWIN',
                    'alamat_pegawai' => 'JALAN DARMAWANGSA NO. 1',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'baghase.prasetyo27@gmail.com',
                    'notelp_pegawai' => '0895636129618',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 167,
                    'beratbadan' => 79,
                ],
                [
                    'nama_pegawai' => 'Yudha Iqbal Ariono',
                    'noidentitas' => '3578102610990005',
                    'nomorindukpegawai' => '153578102610990005',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12410,
                    'kelurahan_id' => 14668,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '1999-10-26',
                    'jeniskelamin' => 'LAKI-LAKI',
                    'statusperkawinan' => 'BELUM KAWIN',
                    'alamat_pegawai' => 'JL Kapas Baru Gang 1 No 92-i , Kel Kapas Madya Baru , Kec Tambaksari',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'yudhaaiqbaal@gmail.com',
                    'notelp_pegawai' => '087826458674',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 170,
                    'beratbadan' => 90,
                ],
                [
                    'nama_pegawai' => 'MEDYANA PUTRI SUHERMAN',
                    'noidentitas' => '3578136509010002',
                    'nomorindukpegawai' => '153578136509010002',
                    'provinsi_id' => 33,
                    'kabupaten_id' => 528,
                    'kecamatan_id' => 12388,
                    'kelurahan_id' => 14564,
                    'tempatlahir_pegawai' => 'Surabaya',
                    'tgl_lahirpegawai' => '2001-09-25',
                    'jeniskelamin' => 'PEREMPUAN',
                    'statusperkawinan' => null,
                    'alamat_pegawai' => 'Jl. Margodadi II/71',
                    'agama' => 'ISLAM',
                    'alamatemail' => 'medyanaputrii@gmail.com',
                    'notelp_pegawai' => '089612623663',
                    'warganegara_pegawai' => 'INDONESIA',
                    'tinggibadan' => 170,
                    'beratbadan' => 90,
                ],
            ];

        foreach ($dataPegawai as $index => $data) {
            $pegawaiItem = Pegawai::create(array_merge($data, [
                'pegawai_aktif' => true,
                'is_admin' => false,
            ]));

            $username = substr(strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $data['nama_pegawai'])), 0, 15) . ($index + 1);

            $userItem = User::create([
                'pegawai_id' => $pegawaiItem->pegawai_id,
                'username' => $username,
                'password' => \Illuminate\Support\Facades\Hash::make('123456'),
                'statusaktif' => true,
            ]);

            $pegawaiItem->update(['loginuser_id' => $userItem->loginuser_id]);
        }

        // Seed Pekerjaan
        $pekerjaans = [
            ['pekerjaan_nama' => 'Pegawai Swasta', 'pekerjaan_aktif' => true],
            ['pekerjaan_nama' => 'PNS / ASN', 'pekerjaan_aktif' => true],
            ['pekerjaan_nama' => 'Wiraswasta', 'pekerjaan_aktif' => true],
            ['pekerjaan_nama' => 'Pelajar / Mahasiswa', 'pekerjaan_aktif' => true],
            ['pekerjaan_nama' => 'Buruh', 'pekerjaan_aktif' => true],
            ['pekerjaan_nama' => 'Ibu Rumah Tangga', 'pekerjaan_aktif' => true],
            ['pekerjaan_nama' => 'Pegawai Rumah Sakit', 'pekerjaan_aktif' => true],
            ['pekerjaan_nama' => 'Lainnya', 'pekerjaan_aktif' => true],
        ];
        foreach ($pekerjaans as $p) {
            \App\Models\Pekerjaan::create($p);
        }

        // Seed Ruangan
        \App\Models\Ruangan::create([
            'ruangan_nama' => 'Unit Transfusi Darah Utama',
            'ruangan_singkatan' => 'UTD Main',
            'pekerjaan_aktif' => true,
        ]);
    }
}
